IN THIS SCRIPT WE DO CLEANING OF RAW DATA

In [5]:
import pandas as pd
import numpy as np
import os

In [8]:
print(os.getcwd())

data = pd.read_csv("../A_DATASOURCE/RAWDATASET/Kia_EV6_Ref_Dataset_Raw_12000.csv")

d:\DATA\PROJECTS\PROJECT_KIA_EV6\PYTHON_SCRIPT

In [9]:
df = data.copy()

In [12]:
df.head()

,Session_ID,Timestamp,Epoch,Source_Log,Vehicle_Speed_kmh,Speed_mps,Accel_X_mps2,Accel_Y_mps2,Accel_Z_mps2,Altitude_m,...,TPMS_FL,TPMS_FR,TPMS_RL,TPMS_RR,TPMS_Avg,Latitude_deg,Longitude_deg,Drive_Context,Estimated_Powertrain_Efficiency_pct,Data_Quality_Flag
0,EV6_628CEDE8,2022-05-24 06:04:30+00:00,1.653372e+09,00000007-628CEDE8,0.0018,0.0005,-0.3750,0.2500,10.0077,46.175,...,37.2,37.2,37.2,37.0,37.15,56.1597,10.2142,Stop_or_Crawl,NaN,OK
1,EV6_6429D341,2023-03-28 05:22:45+00:00,1.679981e+09,00000200-6429D341,12.1278,3.3688,-0.2806,0.9107,10.1046,103.680,...,34.6,33.6,34.6,34.0,34.20,56.1088,10.1517,Urban,-139.2822,OK
2,EV6_63121455,2022-09-01 18:16:50+00:00,1.662056e+09,00000003-63121455,33.9414,9.4282,-0.1709,0.2755,10.0587,110.660,...,38.0,36.8,38.6,38.0,37.85,56.7375,9.7018,Urban,NaN,OK
3,EV6_6429D331,2023-03-26 06:55:35+00:00,1.679814e+09,00000191-6429D331,16.2910,4.5253,1.3546,0.2092,10.0485,106.380,...,34.8,34.2,34.6,34.2,34.45,56.0575,10.1560,Urban,17.5794,OK
4,EV6_62D78C64,2022-07-19 17:20:45+00:00,1.658251e+09,00000002-62D78C64,21.4378,5.9549,-0.1888,0.4464,10.1301,72.120,...,38.6,38.0,38.6,39.6,38.70,56.3983,10.5204,Urban,13.2036,OK

In [15]:
df.columns[5].lower()

'speed_mps'

In [18]:
df.columns.tolist()

['Session_ID',
 'Timestamp',
 'Epoch',
 'Source_Log',
 'Vehicle_Speed_kmh',
 'Speed_mps',
 'Accel_X_mps2',
 'Accel_Y_mps2',
 'Accel_Z_mps2',
 'Altitude_m',
 'Road_Grade_pct',
 'Heading_deg',
 'Pitch_deg',
 'Roll_deg',
 'Aero_Force_N',
 'Rolling_Resistance_N',
 'Grade_Force_N',
 'Inertial_Force_N',
 'Estimated_Road_Load_N',
 'Estimated_Wheel_Power_kW',
 'Estimated_Wheel_Torque_Nm',
 'Estimated_Motor_Torque_Nm',
 'Battery_Voltage_V',
 'Battery_Current_A',
 'Battery_Power_kW',
 'Available_Charge_Power_kW',
 'Available_Discharge_Power_kW',
 'Battery_SOC_pct',
 'SOC_Display_pct',
 'Battery_SOH_pct',
 'Battery_Max_Temp_C',
 'Battery_Min_Temp_C',
 'Battery_Temp_C',
 'Battery_Temp_Spread_C',
 'Max_Cell_Voltage_V',
 'Min_Cell_Voltage_V',
 'Cell_Voltage_Spread_V',
 'Ambient_Temp_C',
 'Distance_Total_km',
 'Distance_Trip_km',
 'TPMS_FL',
 'TPMS_FR',
 'TPMS_RL',
 'TPMS_RR',
 'TPMS_Avg',
 'Latitude_deg',
 'Longitude_deg',
 'Drive_Context',
 'Estimated_Powertrain_Efficiency_pct',
 'Data_Quality_Flag']

In [25]:
df.dtypes

Session_ID                                          object
Timestamp                              datetime64[ns, UTC]
Epoch                                              float64
Source_Log                                          object
Vehicle_Speed_kmh                                  float64
Speed_mps                                          float64
Accel_X_mps2                                       float64
Accel_Y_mps2                                       float64
Accel_Z_mps2                                       float64
Altitude_m                                         float64
Road_Grade_pct                                     float64
Heading_deg                                        float64
Pitch_deg                                          float64
Roll_deg                                           float64
Aero_Force_N                                       float64
Rolling_Resistance_N                               float64
Grade_Force_N                                      float64
Inertial_Force_N                                   float64
Estimated_Road_Load_N                              float64
Estimated_Wheel_Power_kW                           float64
Estimated_Wheel_Torque_Nm                          float64
Estimated_Motor_Torque_Nm                          float64
Battery_Voltage_V                                  float64
Battery_Current_A                                  float64
Battery_Power_kW                                   float64
Available_Charge_Power_kW                          float64
Available_Discharge_Power_kW                       float64
Battery_SOC_pct                                    float64
SOC_Display_pct                                    float64
Battery_SOH_pct                                    float64
Battery_Max_Temp_C                                 float64
Battery_Min_Temp_C                                 float64
Battery_Temp_C                                     float64
Battery_Temp_Spread_C                              float64
Max_Cell_Voltage_V                                 float64
Min_Cell_Voltage_V                                 float64
Cell_Voltage_Spread_V                              float64
Ambient_Temp_C                                     float64
Distance_Total_km                                  float64
Distance_Trip_km                                   float64
TPMS_FL                                            float64
TPMS_FR                                            float64
TPMS_RL                                            float64
TPMS_RR                                            float64
TPMS_Avg                                           float64
Latitude_deg                                       float64
Longitude_deg                                      float64
Drive_Context                                       object
Estimated_Powertrain_Efficiency_pct                float64
Data_Quality_Flag                                   object
dtype: object

In [20]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [ ]:
df["Epoch"] = df["Epoch"].astype("Int64")

#Int data type can handle NaN means missing values ko.

In [38]:
df["Epoch"].sum()

np.int64(19994998501625)

 CHECKING OF MISSING VALUES

In [41]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_%": (df.isnull().mean() * 100).round(2)
})

missing_report[
    missing_report["Missing_Count"] > 0
].sort_values("Missing_Count", ascending=False)

                                     Missing_Count  Missing_%
Ambient_Temp_C                                7928      65.63
Estimated_Powertrain_Efficiency_pct           3650      30.22
TPMS_FR                                        455       3.77
TPMS_FL                                        455       3.77
TPMS_RL                                        455       3.77
TPMS_RR                                        454       3.76
TPMS_Avg                                       441       3.65
Battery_Current_A                              403       3.34
Battery_SOC_pct                                401       3.32
Battery_Voltage_V                              399       3.30
Battery_Temp_C                                 398       3.29
Battery_Max_Temp_C                             378       3.13
Battery_Min_Temp_C                             378       3.13
Battery_Temp_Spread_C                          378       3.13
Min_Cell_Voltage_V                             378       3.13
Cell_Voltage_Spread_V                          378       3.13
Battery_Power_kW                               378       3.13
Max_Cell_Voltage_V                             378       3.13
Available_Discharge_Power_kW                   318       2.63
Battery_SOH_pct                                318       2.63
SOC_Display_pct                                318       2.63
Available_Charge_Power_kW                      318       2.63
Vehicle_Speed_kmh                              152       1.26
Distance_Trip_km                               127       1.05
Roll_deg                                       127       1.05
Speed_mps                                      127       1.05
Epoch                                          127       1.05
Heading_deg                                    127       1.05
Altitude_m                                     127       1.05
Pitch_deg                                      127       1.05
Longitude_deg                                  127       1.05
Latitude_deg                                   127       1.05
Drive_Context                                  127       1.05
Distance_Total_km                              127       1.05
Accel_Z_mps2                                    93       0.77
Accel_Y_mps2                                    93       0.77
Accel_X_mps2                                    93       0.77
Road_Grade_pct                                  75       0.62

In [42]:
df = df.sort_values(
    ["Session_ID", "Timestamp"]
).reset_index(drop=True)

In [44]:
sensor_cols = [
    "TPMS_FL",
    "TPMS_FR",
    "TPMS_RL",
    "TPMS_RR",
    "Battery_Current_A",
    "Battery_SOC_pct",
    "Battery_Voltage_V",
    "Battery_Temp_C",
    "Min_Cell_Voltage_V",
    "Max_Cell_Voltage_V",
    "Available_Discharge_Power_kW",
    "Available_Charge_Power_kW",
    "Vehicle_Speed_kmh",
    "Roll_deg",
    "Heading_deg",
    "Altitude_m",
    "Pitch_deg",
    "Latitude_deg",
    "Longitude_deg",
    "Accel_X_mps2",
    "Accel_Y_mps2",
    "Accel_Z_mps2",
    "Road_Grade_pct"
]

In [45]:
for col in sensor_cols:
    df[col] = (
        df.groupby("Session_ID")[col]
        .transform(
            lambda x: x.interpolate(
                method="linear",
                limit=5,
                limit_area="inside"
            )
        )
    )

In [46]:
df[sensor_cols].isnull().sum()

TPMS_FL                         276
TPMS_FR                         276
TPMS_RL                         276
TPMS_RR                         276
Battery_Current_A               211
Battery_SOC_pct                 212
Battery_Voltage_V               210
Battery_Temp_C                  211
Min_Cell_Voltage_V              210
Max_Cell_Voltage_V              210
Available_Discharge_Power_kW    163
Available_Charge_Power_kW       163
Vehicle_Speed_kmh                95
Roll_deg                         95
Heading_deg                      95
Altitude_m                       95
Pitch_deg                        95
Latitude_deg                     95
Longitude_deg                    95
Accel_X_mps2                     72
Accel_Y_mps2                     72
Accel_Z_mps2                     72
Road_Grade_pct                   45
dtype: int64

                                          PHASE 2 DATA CLEANING

                FOR CLEANING nd HANDLING MISSING DATA FROM VOLTAGE , CURRENT AND POWER

In [52]:
for col in ["Battery_Voltage_V", "Battery_Current_A"]:
    df[col] = (
        df.groupby("Session_ID")[col]
        .transform(
            lambda x: x.interpolate(
                method="linear",
                limit=5,
                limit_area="inside"
            )
        )
    )

In [54]:
df[["Battery_Voltage_V", "Battery_Current_A"]].isna().sum()

Battery_Voltage_V    210
Battery_Current_A    211
dtype: int64

In [53]:
df[["Battery_Voltage_V", "Battery_Current_A"]]

       Battery_Voltage_V  Battery_Current_A
0                  781.2                1.1
1                  779.6               13.7
2                  781.0                1.0
3                    NaN                NaN
4                    NaN                NaN
...                  ...                ...
12075              764.2                2.6
12076              764.3                2.5
12077              766.2              -12.3
12078              765.1                0.0
12079              764.9                0.9

[12080 rows x 2 columns]

In [55]:
df[["Battery_Voltage_V", "Battery_Current_A"]].isna().mean() * 100

Battery_Voltage_V    1.738411
Battery_Current_A    1.746689
dtype: float64

In [56]:
df["Battery_Power_Calculated_kW"] = (
    df["Battery_Voltage_V"] *
    df["Battery_Current_A"]
) / 1000

In [ ]:
df.head()

                 TPMS DATA HANDLING

In [58]:
df["TPMS_Avg_Calculated"] = df[
    ["TPMS_FL", "TPMS_FR", "TPMS_RL", "TPMS_RR"]
].mean(axis=1)

In [ ]:
df[
    [
        "TPMS_FL",
        "TPMS_FR",
        "TPMS_RL",
        "TPMS_RR",
        "TPMS_Avg_Calculated"
    ]
].head(10)

In [60]:
df["TPMS_Avg_Calculated"].isna().sum()

np.int64(276)

#TPMS AVG AND TPMS CALCULATED VALIDATION

# TPMS_Avg_Calculated
        ↓
4 readings available → calculate
some readings available → calculate from available readings
all 4 missing → retain NaN

In [ ]:
df[["TPMS_Avg_Calculated","TPMS_Avg"]]


df[
    [
        "TPMS_FL",
        "TPMS_FR",
        "TPMS_RL",
        "TPMS_RR",
        "TPMS_Avg_Calculated"
    ]
].isna().sum()



# since we have all 4 tpms are NaN we can"t calculate our own decided tpms avg.

TPMS_FL                276
TPMS_FR                276
TPMS_RL                276
TPMS_RR                276
TPMS_Avg_Calculated    276
dtype: int64

                   CELL VOLTAGE SPREAD 
            
             Cell Voltage Spread = Max Cell Voltage − Min Cell Voltage

In [66]:
df["Cal_cell_voltage_spread"] = (df["Max_Cell_Voltage_V"] - df["Min_Cell_Voltage_V"] )

In [68]:
df[
    [   "Min_Cell_Voltage_V",
        "Max_Cell_Voltage_V",
        "Cell_Voltage_Spread_V",
        "Cal_cell_voltage_spread"

    ]
].head(20)

,Min_Cell_Voltage_V,Max_Cell_Voltage_V,Cell_Voltage_Spread_V,Cal_cell_voltage_spread
0,4.06,4.06,0.00,0.00
1,4.04,4.06,0.02,0.02
2,4.06,4.06,0.00,0.00
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN
5,4.06,4.06,0.00,0.00
6,4.06,4.06,0.00,0.00
7,4.06,4.06,0.00,0.00
8,4.06,4.06,0.00,0.00
9,4.06,4.06,0.00,0.00
10,4.06,4.06,0.00,0.00
11,NaN,NaN,NaN,NaN
12,4.04,4.06,0.02,0.02
13,4.06,4.06,0.00,0.00
14,4.06,4.06,NaN,0.00
15,4.06,4.06,0.00,0.00
16,4.06,4.06,0.00,0.00
17,4.06,4.06,0.00,0.00
18,4.04,4.06,0.02,0.02
19,4.02,4.04,0.02,0.02

In [70]:
#Missing check

df["Cal_cell_voltage_spread"
].isna().sum()

np.int64(210)

In [72]:
#Validation
df[
    [
        "Cell_Voltage_Spread_V",
        "Cal_cell_voltage_spread"
    ]
].head(20)

    Cell_Voltage_Spread_V  Cal_cell_voltage_spread
0                    0.00                     0.00
1                    0.02                     0.02
2                    0.00                     0.00
3                     NaN                      NaN
4                     NaN                      NaN
5                    0.00                     0.00
6                    0.00                     0.00
7                    0.00                     0.00
8                    0.00                     0.00
9                    0.00                     0.00
10                   0.00                     0.00
11                    NaN                      NaN
12                   0.02                     0.02
13                   0.00                     0.00
14                    NaN                     0.00
15                   0.00                     0.00
16                   0.00                     0.00
17                   0.00                     0.00
18                   0.02                     0.02
19                   0.02                     0.02

In [75]:
#difference between both

df["Cell_Spread_Difference"] = (
    df["Cell_Voltage_Spread_V"] -
    df["Cal_cell_voltage_spread"]
)

In [76]:
#Goal: difference should between mostly 0 OR extremely close to 0 
df["Cal_cell_voltage_spread"].describe()

count    11870.000000
mean         0.007219
std          0.009619
min          0.000000
25%          0.000000
50%          0.000000
75%          0.020000
max          0.040000
Name: Cal_cell_voltage_spread, dtype: float64